### ISSUE TITLE
Polymorph 0.15 not working with Oh The Biomes You'll Go 1.1.2+

### ISSUE THREAD

**Issue by Lazuli26** [TheIllusiveC4/Polymorph#36]
Hello, I encountered this issue while running my server after adding Polymorph to the mixture

Polymorph (polymorph) encountered an error during the common_setup event phase
§7java.lang.NoClassDefFoundError: voronoiaoc/byg/client/gui/BYGWorkbenchContainer

**Comment by JamesYeoman** [comment]
It appears at some point between `oh the Biomes You'll Go` v1.0.8 and v1.1, the package `voronoiaoc` was renamed to `corgiaoc`. The releases between those two versions seem to be in regards to addressing a change in the way forge handles registries, as if I try to load v1.0.8, I get errors in regards to BYG trying to add to the registries after the registry was locked.

v1.0.8 was released late october

**Comment by TheIllusiveC4** [comment]
Update to Polymorph 0.16.
